import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Layout, Menu } from "antd";
import AppFooter from "../components/Appfooter";
import Image from "next/image";
import { useState } from "react";
import { ContactMe } from "../components/ContactMe";
import { HomePage } from "../components/HomePage";
const Home: NextPage = () => {
  const { Header, Content, Footer } = Layout;
  const [contactMe, setContactMe] = useState<boolean>(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header className={styles.header}>
          <div className={styles.menu}>
            <Menu theme="dark" mode="horizontal" defaultSelectedKeys={["1"]}>
              <Menu.Item onClick={() => setContactMe(false)} key="1">
                Home
              </Menu.Item>
              <Menu.Item key="2">
                <a href="/files/Resume.pdf" download>
                  Resume
                </a>
              </Menu.Item>
              <Menu.Item onClick={() => setContactMe(true)} key="3">
                Contact Me
              </Menu.Item>
            </Menu>
          </div>
        </Header>
        <Content
          className={styles.content}
          style={{ padding: "0 10px", marginTop: 64 }}
        >
          {contactMe ? <ContactMe /> : <HomePage />}
        </Content>
        <Footer
          style={{
            textAlign: "center",
            color: "#ffff",
            backgroundColor: "#001529",
            padding: "5px 50px",
          }}
        >
          <AppFooter />
        </Footer>
      </Layout>
    </div>
  );
};

export default Home;
